services:
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otelcol:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./configs/otel-collector.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - 4317:4317
      - 55679:55679

  zipcode-api:
    build: ./zipcode
    ports:
      - 8000:8000

  weather-api:
    build: ./weather
    ports:
      - 8001:8001
